// Login
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Logout
export const LOGOUT_STARTED = 'LOGOUT_STARTED';
export const LOGOUT_COMPLETE = 'LOGOUT_COMPLETE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
