// Login
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_COMPLETE = 'LOGIN_COMPLETE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Logout
export const LOGOUT_STARTED = 'LOGOUT_STARTED';
export const LOGOUT_COMPLETE = 'LOGOUT_COMPLETE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Register
export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTER_COMPLETE = 'REGISTER_COMPLETE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
