export const GET_EMAILS_SUCCESS = 'GET_EMAILS_SUCCESS';
export const GET_EMAILS_FAIL = 'GET_EMAILS_FAIL';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCES';
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL';
